"""Local voice input prototype."""

from .model_selector import (
    GpuInfo,
    HardwareInfo,
    ModelProfile,
    SelectionRequest,
    SelectionResult,
    detect_hardware,
    get_model_profiles,
    select_model,
)
from .api_provider import (
    DEFAULT_SYSTEM_PROMPT,
    DICTATION_POSTPROCESS_PROMPT,
    FORMAL_REWRITE_PROMPT,
    POSTPROCESS_PRESETS,
    TODO_EXTRACT_PROMPT,
    TRANSLATE_TO_CHINESE_PROMPT,
    ApiProviderError,
    ApiTextResult,
    call_chat_completion,
    get_postprocess_prompt,
    normalize_chat_completions_endpoint,
)
from .api_context import (
    ApiContextPackage,
    build_api_context_package,
    format_api_context_user_text,
    read_recent_transcription_texts,
)
from .app import VoiceInputApp
from .asr import (
    AsrBackend,
    BackendUnavailableError,
    TranscriptionJob,
    TranscriptionError,
    TranscriptionResult,
    TranscriptionSegment,
)
from .config import (
    ApiProviderConfig,
    ApiContextConfig,
    AppConfig,
    AudioConfig,
    HotkeyConfig,
    HotwordConfig,
    QuickCaptureConfig,
    QuickCaptureRule,
    TaskRouteConfig,
    TaskRoutingConfig,
    add_hotwords,
    add_quick_capture_rule,
    clear_hotwords,
    clear_quick_capture_rules,
    load_config,
    save_config,
    selection_for_task,
    set_hotwords_enabled,
    update_api_provider,
    update_config,
    update_task_route,
)
from .audio_capture import AudioCaptureError, AudioInputDevice, RecordingSession, list_input_devices, record_wav
from .sherpa_backend import SenseVoiceModelFiles, SherpaOnnxSenseVoiceBackend
from .text_output import (
    TextOutputError,
    TextOutputResult,
    apply_text_outputs,
    copy_to_clipboard,
    paste_text_via_clipboard,
    read_clipboard_text,
    write_text_file,
)
from .windows_clipboard import ClipboardSnapshot, WindowsClipboard, WindowsClipboardError
from .diagnostics import DiagnosticCheck, format_diagnostics, run_diagnostics
from .hotkey import HotkeyError, HotkeyNames, PushToTalkHotkeyRunner
from .usage_log import TranscriptionLogEntry, append_transcription_log, entry_from_result
from .subtitles import format_srt, format_srt_timestamp, write_srt_file
from .quick_note import QuickNoteMatch, QuickNoteResult, find_quick_note_match, save_quick_note

__all__ = [
    "ApiProviderConfig",
    "ApiContextConfig",
    "AppConfig",
    "AudioCaptureError",
    "AsrBackend",
    "AudioConfig",
    "AudioInputDevice",
    "ApiProviderError",
    "ApiTextResult",
    "ApiContextPackage",
    "BackendUnavailableError",
    "ClipboardSnapshot",
    "DiagnosticCheck",
    "DEFAULT_SYSTEM_PROMPT",
    "DICTATION_POSTPROCESS_PROMPT",
    "FORMAL_REWRITE_PROMPT",
    "GpuInfo",
    "HardwareInfo",
    "HotkeyConfig",
    "HotkeyError",
    "HotkeyNames",
    "HotwordConfig",
    "ModelProfile",
    "POSTPROCESS_PRESETS",
    "QuickCaptureConfig",
    "QuickCaptureRule",
    "QuickNoteMatch",
    "QuickNoteResult",
    "PushToTalkHotkeyRunner",
    "RecordingSession",
    "SelectionRequest",
    "SelectionResult",
    "SenseVoiceModelFiles",
    "SherpaOnnxSenseVoiceBackend",
    "TextOutputError",
    "TextOutputResult",
    "TaskRouteConfig",
    "TaskRoutingConfig",
    "TODO_EXTRACT_PROMPT",
    "TRANSLATE_TO_CHINESE_PROMPT",
    "TranscriptionLogEntry",
    "TranscriptionJob",
    "TranscriptionError",
    "TranscriptionResult",
    "TranscriptionSegment",
    "VoiceInputApp",
    "WindowsClipboard",
    "WindowsClipboardError",
    "add_hotwords",
    "add_quick_capture_rule",
    "apply_text_outputs",
    "append_transcription_log",
    "call_chat_completion",
    "build_api_context_package",
    "clear_hotwords",
    "clear_quick_capture_rules",
    "copy_to_clipboard",
    "detect_hardware",
    "entry_from_result",
    "find_quick_note_match",
    "format_diagnostics",
    "format_srt",
    "format_srt_timestamp",
    "format_api_context_user_text",
    "get_postprocess_prompt",
    "get_model_profiles",
    "list_input_devices",
    "load_config",
    "normalize_chat_completions_endpoint",
    "paste_text_via_clipboard",
    "read_clipboard_text",
    "read_recent_transcription_texts",
    "record_wav",
    "run_diagnostics",
    "save_config",
    "save_quick_note",
    "selection_for_task",
    "select_model",
    "set_hotwords_enabled",
    "update_api_provider",
    "update_config",
    "update_task_route",
    "write_text_file",
    "write_srt_file",
]
